### ISSUE TITLE
「！」や「？」が連続した場合の挙動

### ISSUE THREAD

**Issue by kidayasuo** [w3c/jlreq-d#67]
2024-9-25のミーティングで下のissueについて、議論しました。
https://github.com/w3c/csswg-drafts/issues/10751

このissueによると、中国では「！」や「？」が連続した場合や、これらが閉じ括弧の前に来て「？）」となる場合に、空白を削除することになっているとのこと。ミーティングでは、日本語ではそうではないとコメントする、という結論になりました。

が、よく考えると、少なくとも横書きでの「！？」の詰めは合理的な動作かもしれません。というのは「！？」は長くなりすぎるのです。よって合成ずみの「⁉️」や「⁉︎」がありますが、入力は必ずしも簡単ではありません。

ご意見をお聞かせください。

**Comment by KobayashiToshi** [comment]
>2024-9-25のミーティングで下のissueについて、議論しました。
>w3c/csswg-drafts#10751
>このissueによると、中国では「！」や「？」が連続した場合や、これらが閉じ括弧の前に来て「？）」となる場合に、空白を削除することになっているとのこと。ミーティングでは、日本語ではそうではないとコメントする、という結論になりました。が、よく考えると、少なくとも「！？」はは合理的な動作かもしれません。というのは「！？」は長くなりすぎるのです。よって合成ずみの「⁉️」や「⁉︎」がありますが、入力は必ずしも簡単ではありません。

“！”や“？”が文末に付いた場合，通常は全角アキにします（別の方法もあり，末尾に示す）．文中で使用する場合は，これらの後ろはベタ又は二分アキにします．ですので，文末と文中では配置方法が異なります．また，文末でも“…そうなのか？”といったように終わり括弧の前も空白は入れない．

ですので，文末に付く“！”や“？”の後ろは，一般に和字間隔（U+3000）を使用し，文中で二分アキにする場合は，なんらかの方法で二分アキを確保している．必要な箇所にはアキは入り，不必要な箇所には，空白は入らないようにいる．句読点や括弧と異なり，“！”や“？”の後ろのアキは，“！”や“？”に含まれているわけではなく，なんらかの方法でアキを確保する方法になっている．

ただし，たしかに，連続する場合や，終わり括弧の前にくる場合は，アキは不必要なので，削除するということは，それはそれでよい．

なお，文末でも，横組では，全角でない疑問符等を使用し，二分アキにする方法もあるが，最近は，あまり見掛けない．

**Comment by kidayasuo** [comment]
敏先生、コメントありがとうございます。

中点は両側に四分の空きを持っていますが、？のデザインはそうなっておらず、また空きを削除する想定でデザインしているわけではない、そもそも特に人々から望まれている変更でもない、などの理由で実際には必要性は低いと私も思います。

では当初の合意通り、日本語ではそのようにはしないとのコメントをつけます。

**Comment by KobayashiToshi** [comment]
>中点は両側に四分の空きを持っていますが、？のデザインはそうなっておらず、また空きを削除する想定でデザインしているわけではない、そもそも特に人々から望まれている変更でもない、などの理由で実際には必要性は低いと私も思います。では当初の合意通り、日本語ではそのようにはしないとのコメントをつけます。

これも，疑問符の後ろのアキについて1点追加．現在の問題とは，ちょっとずれるが，以下の問題がある．1行が20字詰として説明します．
　a　19字目に疑問符，20字目に和字間隔（U+3000）がきた場合　→20字目は全角アキ
　b　20字目に疑問符，21字目に和字間隔（U+3000）がきた場合　→和字間隔（U+3000）は削除し，次の行の行頭は空けない．

bの場合，何もしないと次の行頭に和字間隔（U+3000）が配置され，新しい段落と誤解される恐れがあり，このアキは削除したい．この点では，英文の語間スペースと同じ処理にしてほしいところ．しかし，aの場合は，アキを確保するので，英文の場合とは振る舞いが異なる．

**Comment by kidayasuo** [comment]
Closing as resolved.
