### ISSUE TITLE
Why are Japanese glyph variant of HYPHEN, EN DASH, EM DASH important for us?

### ISSUE THREAD

**Issue by kidayasuo** [w3c/jlreq-d#69]
Why are Japanese glyph variant of HYPHEN, EN DASH, EM DASH important for us?

One thing I remember from the past discussion is that their Latin versions are not centered in vertical text. Is this the only reason, e.g. how about horizontal text?

I remember that we might want J version of U+2E3A TWO-EM DASH also.

**Comment by kidayasuo** [comment]
related to https://github.com/w3c/jlreq/issues/276

The following are the characters that we, the JLReq TF, identified as needing Japanese glyph variants.

Unicode|Character name
-- | --
U+2018 | LEFT SINGLE QUOTATION MARK
U+201C | LEFT DOUBLE QUOTATION MARK
U+2019 | RIGHT SINGLE QUOTATION MARK
U+201D | RIGHT DOUBLE QUOTATION MARK
U+2010 | HYPHEN
U+2013 | EN DASH
U+2014 | EM DASH
U+2025 | TWO DOT LEADER
U+2026 | HORIZONTAL ELLIPSIS

**Comment by macnmm** [comment]
@taroyamamoto-451 can comment more fully, but for me there are two key issues: 

Input and encodings: U+2014 is the default on MacOS for what used to be SJIS fullwidth dash, whereas on Windows it is U+2015. This means the Unicode result will differ depending on the IME and platform of the author. This leads, in turn, to problem 2:

Glyph design: U+2014 is intended to be a dash, but it is normally designed for Latin use (i.e. it is lower than centerline and not fully 1 em wide). U+2015 is not a dash, but rather a "bar" with unclear semantic usage, and is nicely in the centerline, which makes it attractive for use with Japanese as a dash surrogate for the SJIS dash. It also 1 em wide and so can be doubled up as is conventional for Japanese double-dash usage. This codepoint not being default on MacOS makes it difficult for DTP pros (on Mac) to use, however.

**Comment by kidayasuo** [comment]
Thank you, Nat (@macnmm). So, setting the platform issue aside, the core issues seem to be: 1) the vertical position too low in horizontal writing, and 2) two consecutive EM DASHes not connecting to each other. Did I understand that correctly?

**Comment by taroyamamoto-451** [comment]
A few new Japanese fonts such as those in the Source Han Sans Pan-CJK font family have glyphs to support both Japanese and Latin forms of dashes including U+2E3A (TWO-EM-DASH) and U+2E3B (THREE-EM-DASH). The forms can be switched automatically if the text is language-tagged. For further information about the font, please refer to:
https://github.com/adobe-fonts/source-han-sans/raw/release/SourceHanSansReadMe.pdf

**Comment by kidayasuo** [comment]
One issue with the language tag is that it is often missing. That said, I agree it is a step forward.

**Comment by kidayasuo** [comment]
It is related, but are there cases where you use an EM DASH or a 三点リーダ alone, without repeating them?

**Comment by taroyamamoto-451** [comment]
Although dashes/ellipses are usually repeated in body texts in Japanese, there are cases where only one Japanese dash/ellipsis is used solely.
1. A Japanese dash is used to indicate a section or interval between two points, places or times, for ex. 東京―京都. (Please pay attention to that an en-dash is used instead for this purpose in Western typography).
2. A single Japanese dash is used before and after a sub-title, for ex., 20世紀前半のタイポグラフィ―伝統性と革新性をめぐって―
3. A single Japanese ellipsis needs to be used in a line in a table of contents, when the space between the end of a chapter/section title and the first digit of its corresponding page number becomes narrower than the total width of (two EMs + 1/4 EM allocated to the fixed space before the number), as shown in the example below.
![三点リーダー](https://github.com/user-attachments/assets/b7dc954b-7c85-4cb0-af3c-579ee4be688f)

**Comment by kidayasuo** [comment]
It is interesting that Japanese typography uses the EM DASH, while English uses the EN DASH to indicate a range. I feel that an EN DASH, as in ‘東京–京都,’ would work equally well between Kanji. It might be that Japanese typography tends to prefer fullwidth characters to avoid triggering adjustments in the spacing between characters.

Regard to the sub-title, isn't single EM DASH too narrow? It might look as if it is also a part of the main title.

The last 三点リーダ is interesting. I guess this kind of filler could be better implemented as an automatic graphic filler between tabs, rather than relying on individual characters.

Anyhow, thank you. I wanted to know when single EM DASH / 三点リーダ are used.

**Comment by kidayasuo** [comment]
Closing as resolved.

**Comment by taroyamamoto-451** [comment]
> I guess this kind of filler could be better implemented as an automatic graphic filler between tabs, rather than relying on individual characters.

I agree. Typesetting command languages for computerized typesetting systems used to support some kind of "fill routines" to do this type of job automatically.
